<?php
namespace Test\Table;

use Doctrine\DBAL\Connection;
use Doctrine\DBAL\DriverManager;
use PHPUnit\Framework\TestCase;

class TableTest extends TestCase
{

	/**
	 * @var Connection
	 */
	private $db;

	/**
	 * @throws \Doctrine\DBAL\DBALException
	 */
	public function setUp()
	{
		$this->db = DriverManager::getConnection([
			'url' => 'sqlite:///:memory:'
		]);
		parent::setUp(); // TODO: Change the autogenerated stub
	}

	public function testGetAllRecords()
	{
		$this->assertTrue(true);
	}

}
